name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check Running Version
        run: go test -cover ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        run: echo 'export PATH=$PATH:$GOPATH/bin' >> ~/.bashrc
        run: source ~/.bashrc

      - name: Formatting Verification
        run: test -z $(go fmt ./...)

      - name: Run Staticcheck
        run: staticcheck ./...
